### ISSUE TITLE
Mimesis seed tests design

### ISSUE THREAD

**Issue by duckyou** [mimesis-lab/discussion#1]
@lk-geimfari 
imho: Write seed tests only for BaseProvider is not such a good idea, like i sayed here https://github.com/lk-geimfari/mimesis/pull/327#issuecomment-352487661
Tests should cover all specific providers methods and catch any method seed issue.
I used constants, but we can init two seeded provider instances and compare it betwen themselves.

**Comment by lk-geimfari** [comment]
@duckyou Also, here yet another problem that if we'll update structure file it'll mean that we should update tests with seed. It's  All this threatens to make of our tests spaghetti.

**Comment by duckyou** [comment]
@lk-geimfari Ok, what if we write seed tests some like this:
```python
@pytest.fixture
def _seeded_providers():
    return Provider(seed=42), Provider(seed=42)

def seed_test(_seeded_providers):
    p1, p2 = _seeded_providers
    assert p1.method_1() == p2.method_1()
    assert p1.method_1() == p2.method_1()
    assert p1.method_1() == p2.method_1()
```
This can resolve `update tests with seed` problem

Spaghetti code problem we can solve by grouping tests by classes
For example:
```python
TestProvider(object):
   pass

TestProviderWithSeed(object):
    pass

```

Tests for seeded providers have other concept than basic tests.
Basic method tests checks data correctness of output. Seed tests checks output data order.
Splitting this tests may speed up debugging

**Comment by lk-geimfari** [comment]
@duckyou I do not see another solution right now. @sobolevn what do you think?
